# Generated by Django 5.2.14 on 2026-05-25 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Индивидуальная'), ('gym', 'Тренажёрный зал'), ('section', 'Секция'), ('workout', 'Воркаут')], default='section', max_length=20, verbose_name='Тип')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Конец')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Мест всего')),
                ('notes', models.TextField(blank=True, verbose_name='Описание / задание')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day', 'time_start'],
            },
        ),
    ]
