# Generated by Django 5.2.14 on 2026-05-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('attended', models.BooleanField(default=False, verbose_name='Явился')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.training', verbose_name='Тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись на тренировку',
                'verbose_name_plural': 'Записи на тренировки',
                'unique_together': {('user', 'training')},
            },
        ),
    ]
