# Generated by Django 5.2.14 on 2026-05-28 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_trainingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Подпись')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created'],
            },
        ),
    ]
