# Generated by Django 5.2.14 on 2026-05-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('coach', 'Тренер'), ('portal_admin', 'Администратор портала')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
