# Generated by Django 5.2.14 on 2026-09-12 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_trainingnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(verbose_name='Ссылка на фото'),
        ),
        migrations.CreateModel(
            name='TrainingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('kind', models.CharField(choices=[('warmup', 'Разминка'), ('main', 'Основная часть'), ('final', 'Заключительная часть')], default='main', max_length=20, verbose_name='Тип блока')),
                ('duration_min', models.PositiveIntegerField(default=10, verbose_name='Длительность, мин')),
                ('equipment', models.CharField(blank=True, max_length=200, verbose_name='Инвентарь')),
                ('description', models.TextField(verbose_name='Содержание блока')),
                ('scheme', models.CharField(blank=True, help_text='Путь к SVG в статике, например schemes/football-slalom.svg', max_length=200, verbose_name='Файл схемы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(blank=True, help_text='Пусто — блок из общей библиотеки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('sport', models.ForeignKey(blank=True, help_text='Оставьте пустым, если блок подходит для любого вида спорта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Блок занятия',
                'verbose_name_plural': 'Блоки занятий',
                'ordering': ['sport__name', 'kind', 'title'],
            },
        ),
    ]
