# Generated by Django 5.2.14 on 2026-09-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_gallery_image_trainingblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingblock',
            name='author',
        ),
        migrations.RemoveField(
            model_name='trainingblock',
            name='created',
        ),
    ]
