# Generated by Django 5.2.14 on 2026-09-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_trainingblock_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='main.sport', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Программа тренировок',
                'verbose_name_plural': 'Программы тренировок',
                'ordering': ['sport__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.PositiveIntegerField(default=1, verbose_name='Занятие')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок в занятии')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.trainingblock', verbose_name='Блок')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.trainingprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Блок программы',
                'verbose_name_plural': 'Блоки программы',
                'ordering': ['session', 'order'],
            },
        ),
    ]
